/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */
/* auto-generated by NAPI-RS (hand-maintained to match src/lib.rs) */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let loadError = null

function isMusl() {
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

function tryRequire(localFile, pkg) {
  try {
    if (existsSync(join(__dirname, localFile))) {
      return require('./' + localFile)
    }
    return require(pkg)
  } catch (e) {
    loadError = e
    return null
  }
}

switch (platform) {
  case 'darwin':
    switch (arch) {
      case 'x64':
        nativeBinding = tryRequire('opendbpylot.darwin-x64.node', 'opendbpylot-darwin-x64')
        break
      case 'arm64':
        nativeBinding = tryRequire('opendbpylot.darwin-arm64.node', 'opendbpylot-darwin-arm64')
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) throw new Error('musl libc is not supported (glibc builds only)')
        nativeBinding = tryRequire('opendbpylot.linux-x64-gnu.node', 'opendbpylot-linux-x64-gnu')
        break
      case 'arm64':
        if (isMusl()) throw new Error('musl libc is not supported (glibc builds only)')
        nativeBinding = tryRequire('opendbpylot.linux-arm64-gnu.node', 'opendbpylot-linux-arm64-gnu')
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        nativeBinding = tryRequire('opendbpylot.win32-x64-msvc.node', 'opendbpylot-win32-x64-msvc')
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) throw loadError
  throw new Error('Failed to load the opendbpylot native binding')
}

const { OpenDbPylot, runCli } = nativeBinding

module.exports.OpenDbPylot = OpenDbPylot
module.exports.runCli = runCli
