/* auto-generated by NAPI-RS (hand-maintained to match src/lib.rs) */
/* eslint-disable */

/** Result of {@link OpenDbPylot.ask}. */
export interface AskResult {
  /** The generated (and self-repaired) SQL. */
  sql: string
  /** Result column names. */
  columns: Array<string>
  /** Result rows (each a list of stringified cells). */
  rows: Array<Array<string>>
  /** How many self-repair round-trips were needed (0 = first attempt worked). */
  repairsUsed: number
  /** A short natural-language answer, when summaries are enabled. */
  answer?: string
}

/** The opendbpylot engine: ask natural-language questions and train the model. */
export class OpenDbPylot {
  /**
   * Load the engine from your saved configuration. Run {@link OpenDbPylot.init}
   * or `dbpylot init` first to configure an LLM provider and a database.
   */
  constructor()
  /** Ask a natural-language question. */
  ask(question: string): AskResult
  /** Teach the model a table definition (DDL). */
  trainDdl(ddl: string): void
  /** Teach the model a business note / documentation string. */
  trainDocumentation(doc: string): void
  /** Teach the model a question → SQL example. */
  trainQuestionSql(question: string, sql: string): void
  /** Run the interactive setup wizard (delegates to the `dbpylot` CLI). */
  static init(): void
  /** Launch the web UI (delegates to the `dbpylot` CLI). */
  static serve(): void
  /** Test the configured LLM + database connections (delegates to `dbpylot`). */
  static doctor(): void
}

/**
 * Run the full `dbpylot` CLI in-process (used by the `dbpylot` bin shim).
 * `args[0]` is the program name. Returns the process exit code.
 */
export function runCli(args: Array<string>): number

